### ISSUE TITLE
which is the parameters of nealmon in midas_r ?

### ISSUE THREAD

**Issue by zhouxiandong** [mpiktas/midasr#47]
Hello, I'm sorry to that  I'm not good at english. Thank you your work for the midas_r package,it's very usefull for me. But there are some problem I can't understand need your hlep.
First, I don't know which is the parameters of nealmon in the function midas_r(). like the code in the user_guide:
eq.r <- midas_r(y ~ trend + mls(x, 0:7, 4, nealmon) + mls(z,0:16, 12, nealmon), start = list(x = c(1, -0.5), z = c(2,0.5, -0.1)))
In this  code ,which is the parameters of function nealmon use?
Second, aslo in the previous code, the lag K is 7 and 16,  but I don't understand why the results of summary(eq.r) only 3 variables as follow:
##
##
##

**Comment by vzemlys** [comment]
In this example there are two nealmon restrictions, one for variable `x` and one for variable `z`. The starting parameters for the optimisation, for the nealmon restriction of`x` variable are in list element `x` and similarly starting parameters for the nealmon restriction of `z` variable are in list element `z`. Note that nealmon restriction depends on the length of parameter, i.e. if you pass vector of length 2, it uses polynomial of order one, if you pass vector of length 3, it uses polynomial of order 2. 

The summary method for midas_r returns the coefficients of MIDAS restriction. The starting values for `x` and for `z` tells midas_r to use exponential polynomials of order 1 and 2 respectively, hence you get the corresponding coefficients (the first coefficient is the multiplier). 

The JSS article (https://www.jstatsoft.org/article/view/v072i04) has a detailed specification of this example, I suggest to study it more carefully.

**Comment by zhouxiandong** [comment]
Thank you very much!

**Comment by zhouxiandong** [comment]
Thanks for your reply!
As you say, i.e **eq.r<-midas_r(y ~ trend + mls(x, 0:7, 4, nealmon) , start = list(x = c(1, -0.5)))**
in this **midas_r()**, is the nealmon equal to **nealmon(q=c(1,-0.5),2,4)** ?
Any more, you say "The summary method for midas_r returns the coefficients of MIDAS restriction. The starting values for x and for z tells midas_r to use exponential polynomials of order 1 and 2 respectively, hence you get the corresponding coefficients (the first coefficient is the multiplier)".
I know the  first coefficient is the multiplier of the "**eq.r$midas_coefficients**", but what the other coefficients mean?
Also in the result of **coef(eq.r)**,  the first coefficient is the multiplier of the "eq.r$midas_coefficients",but I don't understand what the other coefficients represent respectively.
