### ISSUE TITLE
Quantile regression with MIDAS

### ISSUE THREAD

**Issue by TrungLeVn** [mpiktas/midasr#51]
Hi authors, 
Thank you for your amazing package. 
I am just wondering whether you have intentions to develop the MIDAS package with quantile regress application similar to the MIDAS toolbox now? It would be a big push to the package. 
Best,
Trung

**Comment by vzemlys** [comment]
Yes, there is some preliminary code in dev branch. The problem with quantile regression is that it is very sensitive to initial starting values. I have not found out yet how to solve this satisfactorily.

**Comment by varunyadav-github** [comment]
Dear Authors,
Thank you for the package. Is it possible to use forecast using a midas_qr object? I am consistently getting an error:
"(list) object cannot be coerced to type 'double'"
Regards,
Varun

**Comment by vzemlys** [comment]
Forecasting using midas_qr is not supported yet.
