### ISSUE TITLE
How to deal with Monthly data with Daily regressors?

### ISSUE THREAD

**Issue by jaychen888** [mpiktas/midasr#59]
Hi, There.

Unlike weekly or monthly data usually have a fixed 'm' as 7, or 12, the daily data can be influenced by workday and holidays. I've now been facing with a problem that I have to make monthly data such as PMIs as the dependent variate, and, a daily based data such as trading price as the independent variates.  How do I resample the daily variables in order to use the MIDAS regression function?

**Comment by vzemlys** [comment]
Employ fixed m structure. The idea is that for a MIDAS model you only care about influence of fixed number of days on to monthly structure. There is no benefit in applying different midas lag function for different months based on the number of days.

**Comment by jaychen888** [comment]
Thank you, sir.
Then I am assuming a 21 for m to try. My consideration focuse on normal working days a year in general. Based on 365 days, there are 116 days which are either weekend or holidays in China. And average month will have 21 working days. I then resample the high frequency daily data from the most recent day back to the very original day. And I think it is reasonable then to forecast the next one month ahead.

**Comment by vzemlys** [comment]
Yes, your reasoning sounds fine.
