### ISSUE TITLE
starting point issue

### ISSUE THREAD

**Issue by kazimsanlav** [mpiktas/midasr#60]
Hi, I frequently get an error like "Please try other starting values or a different optimization function" in midas_r() function. I have 2 questions regarding this issue: 

As far as I know, parameters in starting value should be the initial points for each of the components of our objective function. For example, if we want to minimize/maximize k which is in a form of k=f(x,y,z), then we need to supply 3 starting points to an optimization algorithm. What exactly are the starting parameters for in the concept of midas_r() function, what are their ranges and how many points do we need to supply?

Do you recommend to try several points for each value in starting value list in a for loop?

**Comment by vzemlys** [comment]
In  the JSS article, the MIDAS model is defined in the form y=f(x,\theta)+\varepsilon, so the starting values should be the \theta. However the \theta in MIDAS model can be composed of several parts: the parameters of the restriction function (midas lag) and the unrestricted coefficients of other variables. The `midas_r` requires explicitly only the starting parameters of the restriction function, and calculates the guess for the other parameters by itself. You could however supply the starting values for all of the parameters in the manner of `nls`, i.e. specify the list with the term names containing the starting values. Note that you can see which starting values where used by inspecting `start_opt` element of the `midas_r` result
