### ISSUE TITLE
Lasso augmented Midas models

### ISSUE THREAD

**Issue by AzamYahya** [mpiktas/midasr#65]
Does `midasr` package has a function for feature selection such as lasso augmented midas model as described in paper [here](https://editorialexpress.com/cgi-bin/conference/download.cgi?db_name=SAEe2013&paper_id=446)?

**Comment by cumpaz** [comment]
Hey,
Very interesting package! Any progress on the lasso version of the model?
Thanks

**Comment by vzemlys** [comment]
Unfortunately no.

**Comment by justly129** [comment]
Hey, I am also very interesting to this package,
Do there has a complete program for lasso-midas now?

**Comment by daimoriwaki** [comment]
i found matlab version of lasso-midas.
http://www.seltenhut.com/clement.marsilli/VariableSelection.html

**Comment by andresxmv** [comment]
> i found matlab version of lasso-midas.
> http://www.seltenhut.com/clement.marsilli/VariableSelection.html

The link dont work now ;(
