### ISSUE TITLE
MIDAS when dependent variable has higher frequency [feature]

### ISSUE THREAD

**Issue by jspoortayd** [mpiktas/midasr#68]
The documentation states that "However we require that m_i >= 1; such that the process y_t is observed at the lowest frequency." 
Is there a way to estimate for cases where y_t is observed at the highest frequency? 
There is literature where this is used (https://www.norges-bank.no/en/Published/Papers/Working-Papers/2015/132015/) and I was wondering if you can implement this option.

**Comment by SAMFVH** [comment]
Also very interested in this! Trying to model monthly dependent variables with quarterly explanatory variables. Multiple papers talk about a Reversed Midas model?

**Comment by sk-dataocean-online** [comment]
Are there any intentions to implement reverse MIDAS? I am very interested in it.
Papers: https://doi.org/10.1016/j.ijforecast.2018.06.004 , https://doi.org/10.1080/03610918.2018.1563148 ,

**Comment by vzemlys** [comment]
There are no plans. If you send me the pdf articles (I do not have access) I might look into.

**Comment by sk-dataocean-online** [comment]
Could you please send me an empty message to sk(at)dataocean.online? I will reply with those pdfs. You know, it's ok to share articles privately, but it's forbidden to upload article pdf files to some public resource.

**Comment by vzemlys** [comment]
Here is the example of how to implement reverse midas using midasr: https://mpiktas.github.io/reverse-midas/reverse_midasr_example.html

**Comment by sk-dataocean-online** [comment]
Awesome work! Thanks!
