### ISSUE TITLE
Question of MIDAS with panel data

### ISSUE THREAD

**Issue by April-sun** [mpiktas/midasr#74]
Hello,
I am trying to using the MIDAS model to analyze the panel data. But now I have some problems about it and I am wondering if you could give me some advice.
 Does your midasr package has a function for panel data?   
If so, Can you share  me some relevant codes or examples ？

Thank"s for your time!

**Comment by vzemlys** [comment]
Panel data is not supported. However you can do frequency alignment with help of function mls and then proceed to estimate the panel data model by hand.
