### ISSUE TITLE
Error in hAh_test()

### ISSUE THREAD

**Issue by QAQ-Ahuahuahuahua** [mpiktas/midasr#75]
Hi there,

When I was trying to use hAh_test() to test my model, I have encountered this error.
`Error in prep_hAh(x) : 
  Unrestricted model cannot be estimated due to the lack of degrees of freedom, testing the restriction is not possible`

The midas model is like this:
`m1 <- midas_r(Y~mls(X1, 0:13, 12, almonp) + mls(X2, 0:4, 3, almonp) + mls(X3, 0:7, 3, almonp) + mls(X4, 0, 1) + mls(Y, 1, 1),start=list(X1=rep(1,3) ,X2=rep(1,3),X3=rep(1,3)))` 

My target variable is a quarterly data, togethered with independent variables: X1,X2,X3,X4. X1 is a weekly data(m=12, four weeks for a month). X2 and X3 are monthly, and X4 is quarterly. All the data are from 2014M1 to 2020M6.

How can I get a right hAh_test value rather than NA?

Any help is greatly appreciated.

**Comment by vzemlys** [comment]
There are more high frequency lags in your
model than there are observations. This means that you cannot estimate
U-MIDAS model and this is why you get an error message saying exactly that.
Hope it helps.

Vaidotas

**Comment by QAQ-Ahuahuahuahua** [comment]
So the way to solve this error is to reduce the total lags in model or increase observations? What's more, if the result of hAh_test() is NA or error, does it mean my midas model with restriction cannot be adopted?

Thanks a lot

**Comment by vzemlys** [comment]
Hi,

Both will help. 

If the hAh_test is NA this only means that you cannot test whether restriction is the correct one. Other criterias for model validity should be used. 

Vaidotas

**Comment by QAQ-Ahuahuahuahua** [comment]
Got it. Thanks!
