### ISSUE TITLE
Regarding k in the mls()

### ISSUE THREAD

**Issue by mandarpriya** [mpiktas/midasr#89]
Sir,
I am new to the mixed frequency regression,
I had read about MIDAS by Ghysels, and thought of trying it out. So i have my  Y = returns  and X = gdp, which is a quarterly data and Y is a monthly data. I could not understand what is k in mls() function. I  wanted to see the regression of GDP on the returns . 
I would be really grateful for your reply.
Thanks 
Mandar Phatak

**Comment by vzemlys** [comment]
k is the lag. See the jss article for examples.
